### ISSUE TITLE
[Bug] Error utterances

### ISSUE THREAD

**Issue by JaeYeopHan** [chayeoi/blog#108]
![image](https://user-images.githubusercontent.com/17924127/97800448-98320400-1c78-11eb-93f4-829b7c228d19.png)

🙏

**Comment by chayeoi** [comment]
확인 감사합니다. 해결했습니다.

최근에 디폴트 브랜치를 main으로 변경 후 도메인을 이전했는데,
utterances가 master 브랜치에 있는 `utterances.json` 설정을 읽는 것 같네요.
